// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private List<Tile> tiles;
	/**
	 * 
	 */
	private List<Node> nodes;
	/**
	 * 
	 */
	private List<Road> roads;
	/**
	 * 
	 */
	private Tile robberTile;

	/**
	 * 
	 */
	public void boardSetup() {
	}

	/**
	 * 
	 * @param player 
	 * @param n1 
	 * @param n2 
	 */
	public void placeRoad(Player player, Node n1, Node n2) {
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	public boolean placeSettlement(Node node, Player player) {
		return false;
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 * @param player 
	 */
	public boolean upgradeToCity(Node node, Player player) {
		return false;
	}

	/**
	 * 
	 * @param tile 
	 */
	public void moveRobberTo(Tile tile) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Node getNodeById(int id) {
		return null;
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public List<Tile> getAdjacentTiles(Node node) {
		return null;
	}
}
