// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public interface BotDecisionPolicy {
	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public PlayerCommand chooseNextCommand(Gameplay game, TurnController turnController);
}
