// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public abstract class Building extends Buildable {
	/**
	 * 
	 */
	private Node location;

	/**
	 * 
	 * @return 
	 */
	public abstract int getPoints();

	/**
	 * 
	 * @return 
	 */
	public abstract int getResourceMultiplier();
}
