// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class CommandResult {
	/**
	 * 
	 */
	private boolean success;
	/**
	 * 
	 */
	private String message;
	/**
	 * 
	 */
	private boolean endsTurn;
}
