// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class ConsoleTextInputSource implements TextInputSource {
	/**
	 * 
	 * @return 
	 */
	public String readLine() {
		return null;
	}
}
