// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class HexCoordinate {
	/**
	 * 
	 */
	private int q;
	/**
	 * 
	 */
	private int r;
	/**
	 * 
	 */
	private int s;
}
