// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class HumanTurnController extends PlayerTurnController {
	/**
	 * 
	 */
	private TextInputSource input;
	/**
	 * 
	 */
	private HumanCommandParser parser;

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 */
	public void takeTurn(Gameplay game, TurnController turnController) {
	}
}
