// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public abstract class PlayerTurnController {
	/**
	 * 
	 */
	private StateJSONWriter stateJSONWriter;

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 */
	public abstract void takeTurn(Gameplay game, TurnController turnController);
}
