// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class RobberController {
	/**
	 * 
	 * @param board 
	 * @param roller 
	 * @param players 
	 */
	public void resolveSeven(Board board, Player roller, List[] players) {
	}

	/**
	 * 
	 * @param players 
	 */
	private void discardIfNeeded(List[] players) {
	}

	/**
	 * 
	 * @param board 
	 * @return 
	 */
	private Tile pickRandomTile(Board board) {
		return null;
	}

	/**
	 * 
	 * @param board 
	 * @param robberTile 
	 * @param roller 
	 * @return 
	 */
	private Player pickVictim(Board board, Tile robberTile, Player roller) {
		return null;
	}

	/**
	 * 
	 * @param from 
	 * @param to 
	 */
	private void stealRandomResource(Player from, Player to) {
	}
}
