// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class TurnController {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private List[] players;
	/**
	 * 
	 */
	private int currentPlayerIndex;
	/**
	 * 
	 */
	private PlacementRules placementRules;
	/**
	 * 
	 */
	private DiceRoller diceRoller;
	/**
	 * 
	 */
	private RobberController robberController;

	/**
	 * 
	 */
	public void startGame() {
	}

	/**
	 * 
	 */
	public void nextTurn() {
	}

	/**
	 * 
	 * @param player 
	 * @param n1 
	 * @param n2 
	 */
	public void handleBuildRoad(Player player, Node n1, Node n2) {
	}

	/**
	 * 
	 * @param player 
	 * @param node 
	 */
	public void handleBuildSettlement(Player player, Node node) {
	}

	/**
	 * 
	 * @param player 
	 * @param node 
	 */
	public void handleUpgradeCity(Player player, Node node) {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public DiceResult handleRoll(Player player) {
		return null;
	}
}
