// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class VisualizerStateSerializer {
	/**
	 * 
	 * @param board 
	 * @return 
	 */
	public String serialize(Board board) {
		return null;
	}
}
