// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class BenefitScoringStrategy implements MoveScoringStrategy {
	/**
	 * 
	 * @param command 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public Double calculateValue(PlayerCommand command, Gameplay game, TurnController turnController) {
		return 0.0;
	}

	/**
	 * 
	 * @param command 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	private boolean leadsToVictoryPoint(PlayerCommand command, Gameplay game, TurnController turnController) {
		return false;
	}

	/**
	 * 
	 * @param cmd 
	 * @return 
	 */
	private boolean isBuildingAction(PlayerCommand cmd) {
		return false;
	}

	/**
	 * 
	 * @param cmd 
	 * @param player 
	 * @return 
	 */
	private boolean resultsInSmallHand(PlayerCommand cmd, Player player) {
		return false;
	}
}
