// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public abstract class BotConstraintHandler {
	/**
	 * 
	 */
	protected BotConstraintHandler next;

	/**
	 * 
	 * @param next 
	 */
	public void setNext(BotConstraintHandler next) {
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public PlayerCommand handle(Gameplay game, TurnController turnController) {
		return null;
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	protected boolean canHandle(Gameplay game, TurnController turnController) {
		return false;
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	protected PlayerCommand createCommand(Gameplay game, TurnController turnController) {
		return null;
	}
}
