// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class BotDecisionPolicy {
	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 * @param strategy 
	 */
	public PlayerCommand chooseNextCommand(Gameplay game, TurnController turnController, MoveScoringStrategy strategy) {
		return null;
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @param legalActions 
	 * @return 
	 */
	private PlayerCommand chooseConstraintCommand(Gameplay game, TurnController turnController, List<PlayerCommand> legalActions) {
		return null;
	}

	/**
	 * 
	 * @param legalActions 
	 * @return 
	 */
	private PlayerCommand chooseBestSpendingAction(List<PlayerCommand> legalActions) {
		return null;
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param legalActions 
	 * @return 
	 */
	private BuildRoadCommand findRoadConnectingSegments(Player player, Board board, List<PlayerCommand> legalActions) {
		return null;
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param start 
	 * @param end 
	 * @return 
	 */
	private boolean connectsNearbyRoadSegments(Player player, Board board, Node start, Node end) {
		return false;
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param node 
	 * @param excludedNode 
	 * @return 
	 */
	private boolean isOneStepFromOwnedRoad(Player player, Board board, Node node, int excludedNode) {
		return false;
	}

	/**
	 * 
	 * @param player 
	 * @param players 
	 * @param turnController 
	 * @return 
	 */
	private boolean isLongestRoadThreatened(Player player, List<Player> players, TurnController turnController) {
		return false;
	}

	/**
	 * 
	 * @param legalActions 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	private BuildRoadCommand findAnyLegalRoad(List<PlayerCommand> legalActions, Gameplay game, TurnController turnController) {
		return null;
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	private ArrayList<Node> getSettlementNodes(Player player) {
		return new ArrayList<>();
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	private ArrayList<Node> getRoadNodes(Player player) {
		return new ArrayList<>();
	}
}
