// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class BotTurnController extends PlayerTurnController {
	/**
	 * 
	 */
	private BotDecisionPolicy botDecisionPolicy;
	/**
	 * 
	 */
	public BotConstraintHandler firstConstraint;
	/**
	 * 
	 */
	private BenefitScoringStrategy strategy;

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 */
	public void takeTurn(Gameplay game, TurnController turnController) {
	}
}
