// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.Map;

/************************************************************/
/**
 * 
 */
public abstract class Buildable {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Map<Resource, Integer> cost;

	/**
	 * 
	 * @return 
	 */
	public abstract Map<Resource, Integer> getCost();
}
