// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class BuildCityCommand implements PlayerCommand {
	/**
	 * 
	 */
	private int nodeId;
	/**
	 * 
	 */
	private int cost;

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult execute(Gameplay game, TurnController turnController) {
		return null;
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 */
	public void undo(Gameplay game, TurnController turnController) {
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public int getCost(Gameplay game, TurnController turnController) {
		return 0;
	}
}
