// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.Map;

/************************************************************/
/**
 * 
 */
public class City extends Building {
	/**
	 * 
	 * @return 
	 */
	public int getPoints() {
		return 0;
	}

	/**
	 * 
	 * @return 
	 */
	public int getResourceMultiplier() {
		return 0;
	}

	/**
	 * 
	 * @return 
	 */
	public Map<Resource, Integer> getCost() {
		return null;
	}
}
