// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.Stack;
import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class CommandManager {
	/**
	 * 
	 */
	private Stack<PlayerCommand> undoStack;
	/**
	 * 
	 */
	private Stack<PlayerCommand> redoStack;

	/**
	 * 
	 * @param command 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult executeCommand(PlayerCommand command, Gameplay game, TurnController turnController) {
		return null;
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public boolean undo(Gameplay game, TurnController turnController) {
		return false;
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public boolean redo(Gameplay game, TurnController turnController) {
		return false;
	}
}
