// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class DiceResult {
	/**
	 * 
	 */
	private int die1;
	/**
	 * 
	 */
	private int die2;

	/**
	 * 
	 * @return 
	 */
	public int sum() {
		return 0;
	}
}
