// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class DiceRoller {
	/**
	 * 
	 * @return 
	 */
	public DiceResult roll() {
		return null;
	}
}
