// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Gameplay {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private List<Player> players;
	/**
	 * 
	 */
	private int roundNum;
	/**
	 * 
	 */
	private int maxRound;
	/**
	 * 
	 */
	private int currentPlayerIndex;
	/**
	 * 
	 */
	private TurnPhase phase;
	/**
	 * 
	 */
	private List<PlayerTurnController> playerTurnControllers;
	/**
	 * 
	 */
	private StateJSONWriter stateJSONWriter;
	/**
	 * 
	 */
	private TurnController turnController;

	/**
	 * 
	 */
	public void runGame() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	/**
	 * 
	 */
	public void isGameOver() {
	}

	/**
	 * 
	 */
	public void printPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getCurrentPlayer() {
		return null;
	}

	/**
	 * 
	 */
	public void advanceToNextPlayer() {
	}
}
