// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class HumanCommandParser {
	/**
	 * 
	 * @param line 
	 * @return 
	 */
	public PlayerCommand parse(String line) {
		return null;
	}
}
