// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public interface MoveScoringStrategy {
	/**
	 * 
	 * @param command 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public Double calculateValue(PlayerCommand command, Gameplay game, TurnController turnController);
}
