// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private List<Tile> adjacentTiles;
	/**
	 * 
	 */
	private int id;

	/**
	 * 
	 * @param road 
	 */
	public void removeRoad(Road road) {
	}
}
