// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class PlacementRules {
	/**
	 * 
	 * @param board 
	 * @param player 
	 * @param n1 
	 * @param n2 
	 * @return 
	 */
	public boolean canPlaceRoad(Board board, Player player, Node n1, Node n2) {
		return false;
	}

	/**
	 * 
	 * @param board 
	 * @param player 
	 * @param node 
	 * @return 
	 */
	public boolean canPlaceSettlement(Board board, Player player, Node node) {
		return false;
	}

	/**
	 * 
	 * @param board 
	 * @param player 
	 * @param node 
	 * @return 
	 */
	public boolean canUpgradeCity(Board board, Player player, Node node) {
		return false;
	}
}
