// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.Map;

/************************************************************/
/**
 * 
 */
public class ResourceTrade {
	/**
	 * 
	 */
	private Map<Resource, Integer> amounts;
}
