// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.Map;

/************************************************************/
/**
 * 
 */
public class Road extends Buildable {
	/**
	 * 
	 */
	private Node start;
	/**
	 * 
	 */
	private Node last;

	/**
	 * 
	 * @return 
	 */
	public Map<Resource, Integer> getCost() {
		return null;
	}
}
