// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class StateJSONWriter {
	/**
	 * 
	 */
	private VisualizerStateSerializer serializer;
	/**
	 * 
	 */
	public String outputPath;

	/**
	 * 
	 * @param board 
	 */
	public void writeState(Board board) {
	}
}
