// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public interface TextInputSource {
	/**
	 * 
	 * @return 
	 */
	public String readLine();
}
