// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class TradeController {
	/**
	 * 
	 * @param from 
	 * @param to 
	 * @param give 
	 * @param receive 
	 * @return 
	 */
	public boolean proposeTrade(Player from, Player to, ResourceTrade give, ResourceTrade receive) {
		return false;
	}

	/**
	 * 
	 * @param player 
	 * @param give 
	 * @param receiveType 
	 * @return 
	 */
	public boolean executeMaritimeTrade(Player player, ResourceTrade give, Resource receiveType) {
		return false;
	}
}
