// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;
import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class TurnController {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private List<Player> players;
	/**
	 * 
	 */
	private int currentPlayerIndex;
	/**
	 * 
	 */
	private PlacementRules placementRules;
	/**
	 * 
	 */
	private DiceRoller diceRoller;
	/**
	 * 
	 */
	private RobberController robberController;

	/**
	 * 
	 */
	public void startGame() {
	}

	/**
	 * 
	 */
	public void nextTurn() {
	}

	/**
	 * 
	 * @param player 
	 * @param n1 
	 * @param n2 
	 */
	public void handleBuildRoad(Player player, Node n1, Node n2) {
	}

	/**
	 * 
	 * @param player 
	 * @param node 
	 */
	public void handleBuildSettlement(Player player, Node node) {
	}

	/**
	 * 
	 * @param player 
	 * @param node 
	 */
	public void handleUpgradeCity(Player player, Node node) {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public DiceResult handleRoll(Player player) {
		return null;
	}

	/**
	 * 
	 * @param player 
	 * @param node 
	 * @param turn 
	 */
	public void handleUndoBuild(Player player, Node node, int turn) {
	}

	/**
	 * 
	 * @param player 
	 * @param start 
	 * @param end 
	 * @param turn 
	 */
	public void handleUndoBuild(Player player, Node start, Node end, int turn) {
	}

	/**
	 * 
	 * @param player 
	 * @param build 
	 */
	public void undoExchangeResources(Player player, Buildable build) {
	}
}
