// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public abstract class Building {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Node location;

	/**
	 * 
	 * @return 
	 */
	public abstract int getPoints();
}