// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Gameplay {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private List<Player> players;
	/**
	 * 
	 */
	private int roundNum;
	/**
	 * 
	 */
	private int maxRound;

	/**
	 * 
	 */
	public void runGame() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	/**
	 * 
	 */
	public void isGameOver() {
	}

	/**
	 * 
	 */
	public void printPoints() {
	}
}
