// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private Building building;
	/**
	 * 
	 */
	private List<Tile> adjacentTiles;
}
