// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.List;
import java.util.Map;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * Map<Resource, Integer
	 */
	private Map<Resource, Integer> resources;
	/**
	 * 
	 */
	private List<Road> roads;
	/**
	 * 
	 */
	private List<Building> buildings;

	/**
	 * 
	 * @param r 
	 * @param amount 
	 */
	public void addResource(Resource r, int amount) {
	}

	/**
	 * 
	 * @return 
	 */
	public int calculatePoints() {
		return 0;
	}

	/**
	 * 
	 * @param t 
	 * @param amount 
	 * @return 
	 */
	public boolean spendResource(Resource t, int amount) {
		return false;
	}
}
