// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Node start;
	/**
	 * 
	 */
	private Node last;
	/**
	 * 
	 */
	private Player owner;
}
