// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int numberToken;
	/**
	 * 
	 */
	private Resource resource;
}
