// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class BuildCityCommand implements PlayerCommand {
	/**
	 * 
	 */
	private int nodeId;
	private Player player;
	private int cost = 5;

	public BuildCityCommand(int nodeId) {
		this.nodeId = nodeId;
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult execute(Gameplay game, TurnController turnController) {
		Player player = game.getCurrentPlayer();
		Board board = game.getBoard();
		if (board.upgradeCity(player, nodeId)) { //If city is built
			this.player = player;
			System.out.print("Upgraded city at node " + nodeId);
			return new CommandResult(true, false, null);
		}
		System.out.print("Build unsuccessful");
		return null;
	}

	public void undo(Gameplay game, TurnController turnController) {
		Board board = game.getBoard();
		Node node = board.getNodes(nodeId);
		board.undoBuild(player, node);
	}

	public int getCost() {
		return cost;
	}
}
