// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/

import java.util.List;

/**
 * 
 */
public class BuildRoadCommand implements PlayerCommand {
	/**
	 * 
	 */
	private int start;
	/**
	 * 
	 */
	private int end;
	private Player player;
	private int cost = 2;

	public BuildRoadCommand(int start, int end) {
		this.start = start;
		this.end = end;
	}
	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult execute(Gameplay game, TurnController turnController) {
		Player player = game.getCurrentPlayer();
		Board board = game.getBoard();
		if (board.placeRoad(player, start, end)) { //If road is built
			this.player = player;
			System.out.print("Built road at (" + start + ", " + end + ")");
			return new CommandResult(true, false, null);
		}
		System.out.print("Build unsuccessful");
		return null;
	}

	public void undo(Gameplay game, TurnController turnController) {
		Board board = game.getBoard();
		Node start = board.getNodes(this.start);
		Node end = board.getNodes(this.end);
		board.undoBuild(player, start, end);
	}

	public int getCost() {
		return cost;
	}

	public boolean leadsToVictoryPoint(Gameplay game, TurnController turnController) {
		Player player = game.getCurrentPlayer();
		Board board = game.getBoard();
		List<Player> players = game.getPlayers();
		Node start = board.getNodes(this.start);
		Node end = board.getNodes(this.end);

		int oldPoints = player.calcPoints(players, board);
		board.placeRoad(player, start, end);
		int newPoints = player.calcPoints(players, board);
		board.undoBuild(player, start, end);

		return oldPoints < newPoints;
	}
}
