// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class GoCommand implements PlayerCommand {
	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult execute(Gameplay game, TurnController turnController) {
		return new CommandResult(true, true, null); //Returns CommandResult, indicating success
	}

	public void undo(Gameplay game, TurnController turnController) {}

	public int getCost() {
		return 0;
	}
}
